// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTXServer.Data;

#nullable disable

namespace ProjectTXServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220806173107_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            RoleId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd"
                        },
                        new
                        {
                            UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            RoleId = "360E601E-92F2-4F08-832B-604A21293258"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectTXServer.Entity.GenderType", b =>
                {
                    b.Property<string>("GenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("GenderType", (string)null);

                    b.HasData(
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            GenderName = "Man"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            GenderName = "Women"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductCover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIntro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductRate")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = "d7cb1572-c3bc-4d14-b3fd-9f0314e842c3",
                            ProductCover = "css/images/product_men1.PNG",
                            ProductDescription = "This is BST Product",
                            ProductIntro = "link clip",
                            ProductName = "The Astronut",
                            ProductRate = 1
                        },
                        new
                        {
                            ProductId = "e36ce996-b97a-476b-805e-96e3ba429c01",
                            ProductCover = "css/images/product_men2.PNG",
                            ProductDescription = "Men T-shirt The Astronut",
                            ProductIntro = "link clip",
                            ProductName = "BST Summer T-shirt",
                            ProductRate = 1
                        },
                        new
                        {
                            ProductId = "6d82c892-ddb6-4fad-be13-d949626fa168",
                            ProductCover = "css/images/product_men3.PNG",
                            ProductDescription = "The King man T shirt make by coton",
                            ProductIntro = "link clip",
                            ProductName = "King man T shirt",
                            ProductRate = 3
                        },
                        new
                        {
                            ProductId = "b50baaa2-e275-4e06-a383-2229170eaeab",
                            ProductCover = "css/images/product_men4.PNG",
                            ProductDescription = "The Anti formalism T-shirt for men",
                            ProductIntro = "link clip",
                            ProductName = "Anti formalism",
                            ProductRate = 3
                        },
                        new
                        {
                            ProductId = "5ff68ca4-7d71-485d-b5b2-1da4015fc6bc",
                            ProductCover = "css/images/product_men5.PNG",
                            ProductDescription = "This is Unifas",
                            ProductIntro = "link clip",
                            ProductName = "Unifas",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "45b2df55-4c1d-4fec-99ee-0f87dd5bc6d4",
                            ProductCover = "css/images/product_men6.PNG",
                            ProductDescription = "Make in china",
                            ProductIntro = "link clip",
                            ProductName = "T shirt for men",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "a38f3b3e-7819-4703-b0e2-89bc781a230d",
                            ProductCover = "css/images/product_men7.PNG",
                            ProductDescription = "This is YourName Product",
                            ProductIntro = "link clip",
                            ProductName = "YourName",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "98ea05ce-290a-47e4-9305-8f6d63bf146f",
                            ProductCover = "css/images/product_men8.PNG",
                            ProductDescription = "T-shirt smile, that is the best for you",
                            ProductIntro = "link clip",
                            ProductName = "T-shirt smile",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "b04d39cc-b017-4531-b5aa-4e5fc9be7e85",
                            ProductCover = "css/images/product_men9.PNG",
                            ProductDescription = "True choise for guy",
                            ProductIntro = "link clip",
                            ProductName = "Magic T-shirt",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "3837b416-4a88-4919-b51f-9e27c5cc2d46",
                            ProductCover = "css/images/product_men10.PNG",
                            ProductDescription = "That is Astronaut",
                            ProductIntro = "link clip",
                            ProductName = "Astronaut",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "fa983979-a9d6-4e2f-acc5-57825e7bb28b",
                            ProductCover = "css/images/product_women1.PNG",
                            ProductDescription = "Headsfer T-shirt for women1 have a passion with SWAG",
                            ProductIntro = "link clip",
                            ProductName = "women1",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "09df7447-8d67-4aba-96bd-1878da562790",
                            ProductCover = "css/images/product_women2.PNG",
                            ProductDescription = "This is women2",
                            ProductIntro = "link clip",
                            ProductName = "women2",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "b26e8f39-9fd6-452d-ba78-3f0596a91161",
                            ProductCover = "css/images/product_women3.PNG",
                            ProductDescription = "This is women3",
                            ProductIntro = "link clip",
                            ProductName = "women3",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "b52851fd-4f18-460b-bb88-ad394f555a97",
                            ProductCover = "css/images/product_women4.PNG",
                            ProductDescription = "This is women4",
                            ProductIntro = "link clip",
                            ProductName = "women4",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "cc9f6991-c49b-490d-b45f-6f59871a007b",
                            ProductCover = "css/images/product_women5.PNG",
                            ProductDescription = "This is women5",
                            ProductIntro = "link clip",
                            ProductName = "women5",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "b7373d44-a780-4dc2-8454-e26f23a39555",
                            ProductCover = "css/images/product_women6.PNG",
                            ProductDescription = "This is women6",
                            ProductIntro = "link clip",
                            ProductName = "women6",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "01eb7d27-cf08-4fc8-a8ea-99d9c9aa122e",
                            ProductCover = "css/images/product_women7.PNG",
                            ProductDescription = "This is women7",
                            ProductIntro = "link clip",
                            ProductName = "women7",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "f5a00158-ce62-4ba7-ae94-ee48d6f81057",
                            ProductCover = "css/images/product_women8.PNG",
                            ProductDescription = "This is women8",
                            ProductIntro = "link clip",
                            ProductName = "women8",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "c3e9c916-b097-4bc0-bad5-396ddd26380f",
                            ProductCover = "css/images/product_women9.PNG",
                            ProductDescription = "This is women9",
                            ProductIntro = "link clip",
                            ProductName = "women9",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "f0a55fb4-5de8-4e30-8cb3-76d2006778fc",
                            ProductCover = "css/images/product_women10.PNG",
                            ProductDescription = "This is women10",
                            ProductIntro = "link clip",
                            ProductName = "women10",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "0d94d990-ee7e-41b3-9dee-c4e79ab0127e",
                            ProductCover = "css/images/product_pantmen1.PNG",
                            ProductDescription = "This is pantman1",
                            ProductIntro = "link clip",
                            ProductName = "pantman1",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "7a2a95ff-4cd4-4ad1-88bc-a192a88d17e8",
                            ProductCover = "css/images/product_pantmen2.PNG",
                            ProductDescription = "This is pantman2",
                            ProductIntro = "link clip",
                            ProductName = "pantman2",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "62c5c6a2-f811-4b8f-8945-fa23466e1f89",
                            ProductCover = "css/images/product_pantmen3.PNG",
                            ProductDescription = "This is pantman3",
                            ProductIntro = "link clip",
                            ProductName = "pantman3",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "e3fb0395-30d1-4bab-8de0-85519ccf972e",
                            ProductCover = "css/images/product_pantmen4.PNG",
                            ProductDescription = "This is pantman4",
                            ProductIntro = "link clip",
                            ProductName = "pantman4",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "86bcfb4f-8134-453c-b325-6dfdc9b8a9e3",
                            ProductCover = "css/images/product_pantmen5.PNG",
                            ProductDescription = "This is pantman5",
                            ProductIntro = "link clip",
                            ProductName = "pantman5",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "c0477977-86f0-4c86-9918-36248dae7909",
                            ProductCover = "css/images/product_pantwomen1.PNG",
                            ProductDescription = "This is pantwoman1",
                            ProductIntro = "link clip",
                            ProductName = "pantwoman1",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "e7631d91-090a-4b76-8f23-80e0a387e474",
                            ProductCover = "css/images/product_pantwomen2.PNG",
                            ProductDescription = "This is pantwoman2",
                            ProductIntro = "link clip",
                            ProductName = "pantwoman2",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "59b54478-7b46-4e7e-8897-286eee9ff598",
                            ProductCover = "css/images/product_pantwomen3.PNG",
                            ProductDescription = "This is pantwoman3",
                            ProductIntro = "link clip",
                            ProductName = "pantwoman3",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "553f45a0-c3a5-418c-b70b-6068ce26d35e",
                            ProductCover = "css/images/product_pantwomen4.PNG",
                            ProductDescription = "This is pantwoman4",
                            ProductIntro = "link clip",
                            ProductName = "pantwoman4",
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "df494828-5e70-45d9-8ebc-5ab49c7fa572",
                            ProductCover = "css/images/product_pantwomen5.PNG",
                            ProductDescription = "This is pantwoman5",
                            ProductIntro = "link clip",
                            ProductName = "pantwoman5",
                            ProductRate = 5
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductInGender", b =>
                {
                    b.Property<string>("GenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GenderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInGender", (string)null);

                    b.HasData(
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "d7cb1572-c3bc-4d14-b3fd-9f0314e842c3"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "e36ce996-b97a-476b-805e-96e3ba429c01"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "6d82c892-ddb6-4fad-be13-d949626fa168"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "b50baaa2-e275-4e06-a383-2229170eaeab"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "5ff68ca4-7d71-485d-b5b2-1da4015fc6bc"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "45b2df55-4c1d-4fec-99ee-0f87dd5bc6d4"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "a38f3b3e-7819-4703-b0e2-89bc781a230d"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "98ea05ce-290a-47e4-9305-8f6d63bf146f"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "b04d39cc-b017-4531-b5aa-4e5fc9be7e85"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "3837b416-4a88-4919-b51f-9e27c5cc2d46"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "fa983979-a9d6-4e2f-acc5-57825e7bb28b"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "09df7447-8d67-4aba-96bd-1878da562790"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "b26e8f39-9fd6-452d-ba78-3f0596a91161"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "b52851fd-4f18-460b-bb88-ad394f555a97"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "cc9f6991-c49b-490d-b45f-6f59871a007b"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "b7373d44-a780-4dc2-8454-e26f23a39555"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "01eb7d27-cf08-4fc8-a8ea-99d9c9aa122e"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "f5a00158-ce62-4ba7-ae94-ee48d6f81057"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "c3e9c916-b097-4bc0-bad5-396ddd26380f"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "f0a55fb4-5de8-4e30-8cb3-76d2006778fc"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "0d94d990-ee7e-41b3-9dee-c4e79ab0127e"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "7a2a95ff-4cd4-4ad1-88bc-a192a88d17e8"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "62c5c6a2-f811-4b8f-8945-fa23466e1f89"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "e3fb0395-30d1-4bab-8de0-85519ccf972e"
                        },
                        new
                        {
                            GenderId = "120da95c-d18c-4ef3-b921-1561af4e3ac2",
                            ProductId = "86bcfb4f-8134-453c-b325-6dfdc9b8a9e3"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "c0477977-86f0-4c86-9918-36248dae7909"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "e7631d91-090a-4b76-8f23-80e0a387e474"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "59b54478-7b46-4e7e-8897-286eee9ff598"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "553f45a0-c3a5-418c-b70b-6068ce26d35e"
                        },
                        new
                        {
                            GenderId = "9156d3b1-14ef-4978-bf5e-c90a29ec057d",
                            ProductId = "df494828-5e70-45d9-8ebc-5ab49c7fa572"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductInProductType", b =>
                {
                    b.Property<string>("ProductTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductTypeId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInProductType", (string)null);

                    b.HasData(
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "d7cb1572-c3bc-4d14-b3fd-9f0314e842c3"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "e36ce996-b97a-476b-805e-96e3ba429c01"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "6d82c892-ddb6-4fad-be13-d949626fa168"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "b50baaa2-e275-4e06-a383-2229170eaeab"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "5ff68ca4-7d71-485d-b5b2-1da4015fc6bc"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "45b2df55-4c1d-4fec-99ee-0f87dd5bc6d4"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "a38f3b3e-7819-4703-b0e2-89bc781a230d"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "98ea05ce-290a-47e4-9305-8f6d63bf146f"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "b04d39cc-b017-4531-b5aa-4e5fc9be7e85"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "3837b416-4a88-4919-b51f-9e27c5cc2d46"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "fa983979-a9d6-4e2f-acc5-57825e7bb28b"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "09df7447-8d67-4aba-96bd-1878da562790"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "b26e8f39-9fd6-452d-ba78-3f0596a91161"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "b52851fd-4f18-460b-bb88-ad394f555a97"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "cc9f6991-c49b-490d-b45f-6f59871a007b"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "b7373d44-a780-4dc2-8454-e26f23a39555"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "01eb7d27-cf08-4fc8-a8ea-99d9c9aa122e"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "f5a00158-ce62-4ba7-ae94-ee48d6f81057"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "c3e9c916-b097-4bc0-bad5-396ddd26380f"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductId = "f0a55fb4-5de8-4e30-8cb3-76d2006778fc"
                        },
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductId = "0d94d990-ee7e-41b3-9dee-c4e79ab0127e"
                        },
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductId = "7a2a95ff-4cd4-4ad1-88bc-a192a88d17e8"
                        },
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductId = "62c5c6a2-f811-4b8f-8945-fa23466e1f89"
                        },
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductId = "e3fb0395-30d1-4bab-8de0-85519ccf972e"
                        },
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductId = "86bcfb4f-8134-453c-b325-6dfdc9b8a9e3"
                        },
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductId = "c0477977-86f0-4c86-9918-36248dae7909"
                        },
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductId = "e7631d91-090a-4b76-8f23-80e0a387e474"
                        },
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductId = "59b54478-7b46-4e7e-8897-286eee9ff598"
                        },
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductId = "553f45a0-c3a5-418c-b70b-6068ce26d35e"
                        },
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductId = "df494828-5e70-45d9-8ebc-5ab49c7fa572"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductType", b =>
                {
                    b.Property<string>("ProductTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductTypeId");

                    b.ToTable("ProductType", (string)null);

                    b.HasData(
                        new
                        {
                            ProductTypeId = "5be64913-28eb-473c-96b6-9c6239fc1c58",
                            ProductTypeName = "Pants"
                        },
                        new
                        {
                            ProductTypeId = "036774b2-9a3a-43a4-bf2e-6201b00fb9c4",
                            ProductTypeName = "Shirt"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.AppRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AppRole");

                    b.HasData(
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd",
                            ConcurrencyStamp = "c09aba0b-808a-4db9-a68f-22d3b94dd17c",
                            Name = "Staff",
                            NormalizedName = "staff",
                            Description = "Staff"
                        },
                        new
                        {
                            Id = "360E601E-92F2-4F08-832B-604A21293258",
                            ConcurrencyStamp = "4b21e314-9e7e-42df-963e-81918a79ddd6",
                            Name = "Admin",
                            NormalizedName = "admin",
                            Description = "Admin"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("UserDoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AppUser");

                    b.HasData(
                        new
                        {
                            Id = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "70287441-de7a-42e0-a6cc-1ed9dd1454d6",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJbW3JFE+keC3X8LGih9ZswjqqzsmSuqBQ68G1TrZ6FZUnhP7TI+9T1P2r8cznN9Og==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b37b56d0-3679-490c-8045-9611d5c6504f",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            UserDoB = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserFirstName = "admin first name",
                            UserLastName = "admin last name",
                            UserPhoneNumber = "08658568790"
                        },
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0d3568d-2e28-46a2-8bd0-033907897252",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMWbI5yfEoPHOD0gdjbiT1gA0Tpq52yA3fXsiYEESIukCa0rgTi8l4NjkWkqFxTnEw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "53053ae9-03ad-494e-a25a-b0552d7f130a",
                            TwoFactorEnabled = false,
                            UserName = "Staff",
                            UserDoB = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserFirstName = "staff first name",
                            UserLastName = "staff last name",
                            UserPhoneNumber = "08658568790"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductInGender", b =>
                {
                    b.HasOne("ProjectTXServer.Entity.GenderType", "GenderObj")
                        .WithMany("ListGender")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTXServer.Entity.Product", "ProductObj")
                        .WithMany("ListProductGender")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenderObj");

                    b.Navigation("ProductObj");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductInProductType", b =>
                {
                    b.HasOne("ProjectTXServer.Entity.Product", "ProductObj")
                        .WithMany("ListProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTXServer.Entity.ProductType", "ProductTypeObj")
                        .WithMany("ListType")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductObj");

                    b.Navigation("ProductTypeObj");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.GenderType", b =>
                {
                    b.Navigation("ListGender");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.Product", b =>
                {
                    b.Navigation("ListProduct");

                    b.Navigation("ListProductGender");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductType", b =>
                {
                    b.Navigation("ListType");
                });
#pragma warning restore 612, 618
        }
    }
}
